### PR TITLE
Improved functionality and cleaner code

### PR DESCRIPTION
**Pull request by na-stewart**
Many changed were made to improve the functionality of the data manager, and to improve the readability of the code.

### CODE REVIEW

**Comment by sw1pe** [comment]
more commits

**Comment by fogerd** [comment]
From first glance this PR looks like it has a lot of good changes, but it's confusing for me as the reviewer to know what to be looking for. Take a look at this article, its one of the first ones the shows up from a google search, I'm sure I can find something better for ya, but think it nails some good points. 

- [The Anatomy of a Perfect Pull Request](https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067
)

Read through it, but the recap does a good job of capturing the feedback I would leave here. The PR should do one thing, be kept as small as possible to make the change you want, and have a good title / description (you have some more detail in a comment here which is good, but I should be able to tell what's happening from the title. "Many changed were made" doesn't help me much :p

**Comment by fogerd** [comment]
You tell me what you want to do, either I can try and tackle this guy as is and it will likely take me awhile, or you can split him up into more bite sized chunks that I can digest more quickly

**Comment by na-stewart** [comment]
Thanks dennis, I’ll get back to you on this and I will read it over.

Sent from Mail for Windows 10

**Pull request merged**
